export const doctorSlots = [
  {
    id: 1,
    time: '09:00 AM',
    patientId: 101,
    patient: 'Ahmed Mohamed',
    type: 'Follow-up',
    room: 'Clinic 04',
    notes: 'Review BP readings and current medication response.',
  },
  {
    id: 2,
    time: '10:30 AM',
    patientId: 102,
    patient: 'Mona Samir',
    type: 'Consultation',
    room: 'Clinic 02',
    notes: 'Discuss glucose trend and diet plan adjustments.',
  },
  {
    id: 3,
    time: '01:00 PM',
    patientId: 103,
    patient: 'Khaled Adel',
    type: 'Review',
    room: 'Clinic 07',
    notes: 'Evaluate skin reaction progress after treatment.',
  },
];

export const doctorPatients = [
  {
    id: 101,
    name: 'Ahmed Mohamed',
    age: 42,
    gender: 'Male',
    bloodGroup: 'O+',
    condition: 'Hypertension',
    allergies: 'None',
    phone: '+20 10 1234 5678',
    lastVisit: '01 Apr 2026',
  },
  {
    id: 102,
    name: 'Mona Samir',
    age: 35,
    gender: 'Female',
    bloodGroup: 'A+',
    condition: 'Diabetes Type II',
    allergies: 'Penicillin',
    phone: '+20 11 8877 6655',
    lastVisit: '29 Mar 2026',
  },
  {
    id: 103,
    name: 'Khaled Adel',
    age: 29,
    gender: 'Male',
    bloodGroup: 'B+',
    condition: 'Skin Allergy',
    allergies: 'Dust',
    phone: '+20 12 4466 9911',
    lastVisit: '18 Mar 2026',
  },
];
